server:
  port: '8082'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password1!112222225464646
    url: jdbc:mysql://localhost:3306/dcbapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer with Dominik!!
